<?php

namespace SenseiTarzan\Jobs\Class\Job;

use pocketmine\console\ConsoleCommandSender;
use pocketmine\lang\Language;
use pocketmine\Server;

class JobCommandSender extends ConsoleCommandSender
{
    public function __construct(private readonly Job $job, Server $server, Language $language)
    {
        parent::__construct($server, $language);
    }

    public function getName(): string
    {
        return $this->job->getName(); // TODO: Change the autogenerated stub
    }
}